builds:
  - env:
      - CGO_ENABLED=0
    binary:
      lokalise
    goos:
      - darwin
      - windows
      - linux
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386

archives:
  - replacements:
      386: i386
      amd64: x86_64

    format_overrides:
      - goos: windows
        format: zip

    name_template: "lokalise_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*

brews:
  - github:
      owner: lokalise
      name: homebrew-brew
    folder: Formula
    homepage: "https://docs.lokalise.co/api-and-cli/lokalise-cli-tool"
    description: "Lokalise CLI Tool - API client binary"
    skip_upload: false
    name: lokalise

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - lokalise
    image_templates:
      - "lokalise/lokalise-cli:latest"
      - "lokalise/lokalise-cli:{{ .Tag }}"
    skip_push: true
    dockerfile: Dockerfile
